[package]
name = "datapipe-cli"
version = "0.3.0"
edition = "2021"
authors = ["Varun"]
license = "MIT"
repository = "https://github.com/varuns2903/datapipe"
homepage = "https://github.com/varuns2903/datapipe"
documentation = "https://varuns2903.github.io/datapipe/"
description = "A high-performance, streaming-first CLI for structured data"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
clap_complete = "4.4"
anyhow = "1.0"
thiserror = "1.0"
indexmap = { version = "2.14.1", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
csv = "1.4.0"
miette = { version = "7.6.0", features = ["fancy"] }
rayon = "1.12.0"
tempfile = "3.27.0"
clap_mangen = "0.3.3"
rand = "0.10.2"
regex = "1.13.1"
toml = "1.1.5"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
flate2 = "1.1.10"
ruzstd = "0.9.0"

[dev-dependencies]
assert_cmd = "2.0"
criterion = "0.8.2"
predicates = "3.0"

[[bin]]
name = "dp"
path = "src/main.rs"

[[bench]]
name = "bench"
harness = false

[lib]
name = "datapipe"
path = "src/lib.rs"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
